---
- name: Docker Installation
  hosts: app_prod
  remote_user: cddeploy
  become_method: sudo
  gather_facts: false
  vars_files:
    - root_password.yml
  vars:
    ansible_become_pass: "{{ sudo_pass }}"
    docker_installation: "/home/cddeploy/docker"
    package: "docker"

  tasks:
    - name: Create docker directory
      tags: deploy
      file:
        path: "{{ docker_installation }}"
        state: directory
        mode: '0755'
    
    - name: Install Docker if not present
      package:
        name: "{{ package }}"
        state: present

    - name: Install node if not present
      package:
        name: "python3-docker"
        state: present
      become: true

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull the courier_management image
      shell:
        cmd: docker save -o /home/cddeploy/docker/courier_mgmt.tar 192.168.0.130:5000/courier_mgmt:latest
      become: true

    - name: Copy from controller to prod server
      tags: deploy
      copy:
          src: /home/cddeploy/docker/courier_mgmt.tar
          dest: /home/cddeploy/docker/courier_mgmt.tar
    
    - name: Stop a container
      docker_container:
        name: courier
        state: stopped
      vars:
        ansible_python_interpreter: /usr/bin/python3
    
    - name: Load image from archive and push to a private registry
      docker_image:
        name: courier_mgmt
        load_path: /home/cddeploy/docker/courier_mgmt.tar
        source: load